"""create adjustments table

Revision ID: 8bd5cca79952
Revises: c84aa5948943
Create Date: 2026-10-05 01:20:27.889725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd5cca79952'
down_revision: Union[str, Sequence[str], None] = 'c84aa5948943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('doctor_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('center_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_amount <> 0', name='ck_adjustments_amount_nonzero'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustments_recorded_by'), 'adjustments', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_adjustments_transaction_id'), 'adjustments', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustments_transaction_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_recorded_by'), table_name='adjustments')
    op.drop_table('adjustments')
    # ### end Alembic commands ###
