"""add login lockout columns to users

Revision ID: c84aa5948943
Revises: 9da1262da4b3
Create Date: 2026-10-04 09:40:54.950886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84aa5948943'
down_revision: Union[str, Sequence[str], None] = '9da1262da4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
