"""create transactions table

Revision ID: d369d36d1ad9
Revises: 4c1a80d15898
Create Date: 2026-09-01 20:07:26.039319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd369d36d1ad9'
down_revision: Union[str, Sequence[str], None] = '4c1a80d15898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('doctor_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('center_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('doctor_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('center_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('center_percentage >= 0 AND center_percentage <= 100', name='ck_transactions_center_pct_range'),
    sa.CheckConstraint('doctor_percentage >= 0 AND doctor_percentage <= 100', name='ck_transactions_doctor_pct_range'),
    sa.CheckConstraint('total_amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_doctor_id'), 'transactions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_transactions_patient_id'), 'transactions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_transactions_recorded_by'), 'transactions', ['recorded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_recorded_by'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_patient_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_doctor_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
